[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[functions]
  directory = "netlify/functions"

[headers]
  [[headers.for]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
